PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?tag_iri a ex:Tag ;
  ex:tag_id ?tag_id;
  ex:name ?tag_name ;
} 
FROM <file:tags.csv> 
WHERE {
    BIND (IRI(CONCAT('http://ex.org/tags/', ?tag_name)) AS ?tag_iri)

}